//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orchestrator.WebUI.Resource.Vehicle {
    
    
    public partial class VehicleRequiringService {
        
        /// <summary>
        /// lblSeviceDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSeviceDate;
        
        /// <summary>
        /// rdiMOTDueDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadDatePicker rdiMOTDueDate;
        
        /// <summary>
        /// btnGetVehicles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGetVehicles;
        
        /// <summary>
        /// MyClientSideAnchor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Codesummit.WebModalAnchor MyClientSideAnchor;
        
        /// <summary>
        /// dgVehicles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Grid dgVehicles;
        
        /// <summary>
        /// RegNoTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate RegNoTemplate;
        
        /// <summary>
        /// ServiceHistoryTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate ServiceHistoryTemplate;
        
        /// <summary>
        /// SliderTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate SliderTemplate;
        
        /// <summary>
        /// LoadingFeedbackTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate LoadingFeedbackTemplate;
    }
}
